// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: false },

  // Modules
  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxtjs/i18n',
    '@pinia/nuxt',
    '@nuxtjs/color-mode',
    '@nuxtjs/google-fonts'
  ],

  // TypeScript configuration
  typescript: {
    typeCheck: true
  },

  // CSS
  css: ['./assets/css/main.css'],

  // i18n configuration
  i18n: {
    locales: [
      { code: 'en', name: 'English', file: 'en.json' },
      { code: 'it', name: 'Italiano', file: 'it.json' },
      { code: 'es', name: 'Español', file: 'es.json' },
      { code: 'fr', name: 'Français', file: 'fr.json' }
    ],
    defaultLocale: 'en',
    strategy: 'no_prefix',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      redirectOn: 'root'
    },
    langDir: 'locales',
    restructureDir: ''
  },

  // Color mode configuration
  colorMode: {
    classSuffix: ''
  },

  // Google Fonts
  googleFonts: {
    families: {
      Geist: [100, 200, 300, 400, 500, 600, 700, 800, 900],
      'Geist Mono': [100, 200, 300, 400, 500, 600, 700, 800, 900]
    }
  },

  // Runtime config
  runtimeConfig: {
    public: {
      environment: process.env.NUXT_PUBLIC_ENVIRONMENT || 'development'
    }
  },

  // Dev server configuration for Docker
  devServer: {
    host: '0.0.0.0',
    port: 3000
  },

  // App configuration
  app: {
    head: {
      title: 'Create Nuxt App',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'Generated by create nuxt app' }
      ]
    }
  }
})
