volumes:
  mysql_volume:


services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=example@mail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

    ports:
      # The HTTP/S port
      - 80:80
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

  app:
    build:
      context: ./app
    image: app
    container_name: app
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=PathPrefix(`/`)
      # - traefik.http.routers.app.rule=Host(`app.dev`)
      # - traefik.http.routers.app.tls=true
      # - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.services.app.loadbalancer.server.port=3000
    environment:
      TZ: Europe/Rome
    volumes:
      - ./app:/home/node/app
    restart: always

  api:
    build:
      context: ./api
    image: api
    container_name: api
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
      # - traefik.http.routers.api.tls=true
      # - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.services.api.loadbalancer.server.port=5000
    environment:
      TZ: Europe/Rome
      ENVIRONMENT: development
    volumes:
      - ./api:/home/node/api
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: demoPwd
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - mysql_volume:/var/lib/mysql
