networks:
  web:
    external: false
services:
  traefik:
    image: 'traefik:v3.2'
    container_name: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './letsencrypt:/letsencrypt'
    networks:
      - web
    depends_on:
      - app
      - api
  app:
    build:
      context: ./app
      target: 'image-${ENV}'
      args:
        NEXT_PUBLIC_ENVIRONMENT: '${ENV}'
    image: app
    container_name: app
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=PathPrefix(`/`)
      - traefik.http.services.app.loadbalancer.server.port=3000
    environment:
      TZ: Europe/Rome
      NEXT_PUBLIC_ENVIRONMENT: '${ENV}'
    networks:
      - web
    restart: always
  api:
    build:
      context: ./api
    image: api
    container_name: api
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
      - traefik.http.routers.swagger-ui.rule=PathPrefix(`/swagger-ui`)
      - traefik.http.services.api.loadbalancer.server.port=5000
    env_file:
      - .env
    networks:
      - web
    restart: always
