volumes:
  pgdata: null
  valkeydata: null
  esdata: null

services:
  app:
    develop:
      watch:
        - action: sync
          path: ./app/src
          target: /app/src
          ignore:
            - ./app/node_modules/
        - action: rebuild
          path: ./app/package.json
    volumes:
      - /app/node_modules
    restart: unless-stopped
    environment:
      APP_PORT: 4200

  api:
    develop:
      watch:
        - action: sync
          path: ./api
          target: /src
          ignore:
            - ./api/bin/
            - ./api/obj/
        - action: rebuild
          path: ./api/Api/Api.csproj
    restart: always
    depends_on:
      postgres_db:
        condition: service_healthy
      valkey:
        condition: service_started

  postgres_db:
    image: "postgres:18.1"
    container_name: postgres_db
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: "valkey/valkey:9"
    container_name: valkey
    command: valkey-server --port 6379 --cluster-enabled no --requirepass ${VALKEY_PASS}
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "valkeydata:/data"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:9.2.4"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"

  kibana:
    image: "docker.elastic.co/kibana/kibana:9.2.4"
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
