import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'

import Counter from '../src/components/counter/Counter'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  // Fetch data from external API - SSR
  const res: Response = await fetch('http://traefik/api/healthcheck/ping')
  const data: string = await res.json()
  // Pass data to the page via props
  return { props: { data } }
}

const Home: NextPage = (data) => {
  useEffect(() => {
    ping()
    console.log(data)
  })

  const ping = async () => {
    // NOT SSR
    const res: Response = await fetch('http://localhost/api/healthcheck/ping', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
      }
    })
    const data: string = await res.json()
    console.log(data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
        <Counter />
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
